trigger:
  branches:
    include:
    - '*'

variables:
  buildConfiguration: 'Debug'
  isDevelopment: contains(variables['build.sourceBranch'], 'development')
  isMain: contains(variables['build.sourceBranch'], 'main')

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
    - job: 'api_build_and_test'
      displayName: 'API Build & Test'
      steps:
      - template: Pipelines/Api/Templates/build-test.yml
        parameters:
          buildConfiguration:  variables.buildConfiguration
          projectsFilter: '**/*.csproj'
          testProjectsFilter: '**/*Tests.csproj'
          runImplementationTests: true
          runUnitTests: true
          ${{ if or(eq(variables.isDevelopment, true), eq(variables.isMain, true)) }}:
            runIntegrationTests: true
          ${{ if eq(variables.isMain, true) }}:
            runSmokeTests: true
          ${{ if or(eq(variables.isDevelopment, true), eq(variables.isMain, true)) }}:
            publishArtifact: true

 - stage: deploy_dev2
    dependsOn: build
    condition: eq(variables.isDevelopment, true)
    displayName: 'Deploy App to Dev Slot'
    jobs:
      - job:  deploy
        displayName: 'Deploy API'
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: 'Download Artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy API'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'rg-zoo-devd'
            appType: 'webApp'
            WebAppName: 'app-zoo-dev'
            deployToSlotOrASE: true
            ResourceGroupName: 'rg-zoo-dev'
            packageForLinux: '$(System.DefaultWorkingDirectory)/drop/AspNetCore.zip'