import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import SideBar from '../components/dashboard/side-bar'
import Script from 'next/script'

const Home: NextPage = () => {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <>
    <div className="flex min-h-screen overflow-hidden">
      <div className='relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden'>
              <Head>
        <title>Inpark Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Velkommen til Inpark admin panel!
        </h1>
      </main>

      </div>
    </div>
    </>
  )
}

export default Home
