// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD25ZV0tZ1xT9SpkxhZmMLHlkGI58liLsA',
    appId: '1:237063156596:web:6c1b27050a495d4b26f221',
    messagingSenderId: '237063156596',
    projectId: 'zooinator',
    authDomain: 'zooinator.firebaseapp.com',
    storageBucket: 'zooinator.appspot.com',
    measurementId: 'G-CZQQ3WV2Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3h7O3S4bFKdebGB0okmhtocLVFYb6bk',
    appId: '1:237063156596:android:3b616501ba84d13f26f221',
    messagingSenderId: '237063156596',
    projectId: 'zooinator',
    storageBucket: 'zooinator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jhYhgLEW5eJBRaF46H4AQzCOujN18r4',
    appId: '1:237063156596:ios:36b6c9066f7cdbfe26f221',
    messagingSenderId: '237063156596',
    projectId: 'zooinator',
    storageBucket: 'zooinator.appspot.com',
    iosClientId: '237063156596-q7vo8jb9fhst88bhi5tl8bcsfubrmrok.apps.googleusercontent.com',
    iosBundleId: 'dk.zooinator.zoo',
  );
}
