trigger:
  branches:
    include:
    - '*'

variables:
  buildConfiguration: 'Debug'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: 'API_Build_And_Test'
      steps:
      - template: Templates/build-test.yml
        parameters:
          buildConfiguration: Debug
          projectsFilter: '**/*.csproj'
          testProjectsFilter: '**/*Tests.csproj'
          testCategory: 'UnitTest'