trigger:
  branches:
    include:
    - '*'
    exclude:
    - main
    - development

variables:
  buildConfiguration: 'Debug'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: 'API_Build_And_Test'
      steps:
      - template: Templates/build-test.yml
        parameters:
          buildConfiguration: Debug
          projectsFilter: '**/*.csproj'
          testProjectsFilter: '**/*Tests.csproj'
          runImplementationTests: true
          runUnitTests: true
          runIntegrationTests: true
          publishArtifact: false