global using OneOf;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Zoo.Common;
global using Zoo.Common.Api;
global using FluentValidation;
global using Microsoft.AspNetCore.Http;
global using Zoo.Payments.Extensions;
global using Zoo.Payments.Entities;